#!/bin/bash
python fine_tune_multi_triplet_runner.py 1 0 20
python fine_tune_multi_triplet_runner.py 1 1 20
python fine_tune_multi_triplet_runner.py 1 2 20
python fine_tune_multi_triplet_runner.py 1 3 20
python fine_tune_multi_triplet_runner.py 1 4 20
python fine_tune_multi_triplet_runner.py 1 5 20
python fine_tune_multi_triplet_runner.py 1 6 20
python fine_tune_multi_triplet_runner.py 1 8 20
python fine_tune_multi_triplet_runner.py 1 9 20
python fine_tune_multi_triplet_runner.py 5 0 30
python fine_tune_multi_triplet_runner.py 5 1 30
python fine_tune_multi_triplet_runner.py 5 2 30
python fine_tune_multi_triplet_runner.py 5 3 30
python fine_tune_multi_triplet_runner.py 5 4 30
python fine_tune_multi_triplet_runner.py 5 5 30
python fine_tune_multi_triplet_runner.py 5 6 30
python fine_tune_multi_triplet_runner.py 5 7 30
python fine_tune_multi_triplet_runner.py 5 8 30
python fine_tune_multi_triplet_runner.py 5 9 30
python fine_tune_multi_triplet_runner.py 10 0 40
python fine_tune_multi_triplet_runner.py 10 1 40
python fine_tune_multi_triplet_runner.py 10 2 40
python fine_tune_multi_triplet_runner.py 10 3 40
python fine_tune_multi_triplet_runner.py 10 4 40
python fine_tune_multi_triplet_runner.py 10 5 40
python fine_tune_multi_triplet_runner.py 10 6 40
python fine_tune_multi_triplet_runner.py 10 7 40
python fine_tune_multi_triplet_runner.py 10 8 40
python fine_tune_multi_triplet_runner.py 10 9 40
python fine_tune_multi_triplet_runner.py 25 0 50
python fine_tune_multi_triplet_runner.py 25 1 50
python fine_tune_multi_triplet_runner.py 25 2 50
python fine_tune_multi_triplet_runner.py 25 3 50
python fine_tune_multi_triplet_runner.py 25 4 50
python fine_tune_multi_triplet_runner.py 25 5 50
python fine_tune_multi_triplet_runner.py 25 6 50
python fine_tune_multi_triplet_runner.py 25 7 50
python fine_tune_multi_triplet_runner.py 25 8 50
python fine_tune_multi_triplet_runner.py 25 9 50